### ISSUE TITLE
Source for 86-pin edge connectors?

### ISSUE THREAD

**Issue by ralphw** [awasson/AVI-ELF-II#1]

**Comment by awasson** [comment]
Lines 69/70 in the BOM spreadsheet under Digikey, which is linked on the main page and in the Wiki Assembly Manual. The more expensive Green ones line 69 of the spreadsheet are period correct and probably the better choice. The less expensive alternative is also available at Mouser on the Mouser page in the BOM.

**Comment by ralphw** [comment]
Thanks!

**Comment by awasson** [comment]
Your welcome. Any time!
